replicasCount: 1
maxUnavailableCount: 0

image:
  repository: registry.videocoin.net/cloud/staking
  tag: latest
  pullPolicy: IfNotPresent
  pullSecrets: 
  - name: regcred

serviceAccount:
  name: default

service:
  ports: 
    http: 80

resources:
  limits:
   cpu: 100m
   memory: 128Mi
  requests:
   cpu: 10m
   memory: 16Mi

ingress:
  enabled: true
  host: staking.dev.videocoin.net
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-dns-prod
    kubernetes.io/ingress.class: nginx
  secret: tls-cert-staking

config:
  nginx.conf: |
    events {
        worker_connections 1024;
    }

    http {
        include /etc/nginx/mime.types;

        server {
            listen 80;
            server_name localhost;
            root /usr/share/nginx/html;

            location / {
                try_files $uri /index.html;
            }

            location /app {
                try_files $uri /index.html;
            }
        }
    }
